apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: guilherme.maas
          repo: linuxtips-helm-chart
          #tokenRef:
          #  secretName: github-token
          #  key: token
        requeueAfterSeconds: 60    
  template:
    metadata:
      name: 'stack-apps-{{branch_slug}}-{{number}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/guilhermemaas/linuxtips-helm-chart.git
        targetRevision: '{{target_branch}}'
        path: day1/chart/
      destination:
        server: https://kubernetes.default.svc
        namespace: 'apps-of-apps-{{branch_slug}}-{{number}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
